### ISSUE TITLE
Tag all released versions

### ISSUE THREAD

**Issue by joelpurra** [putdotio/putio-kodi#9]
Noticed in the commits and in Kodi that v2.2.1 is out. It is not on the github release page though, where I had expected to find it.

- https://kodi.tv/addon/plugins-video-add-ons/putio
- https://github.com/putdotio/putio-kodi/releases

**Comment by joelpurra** [comment]
The current release (v2.3.0) was properly tagged; the old release (v2.2.1) is outdated. Closing.

**Comment by joelpurra** [comment]
I note that v2.3.1 was published -- great! Can the commit (in this repository) with the code that got published also be tagged, for future reference?

**Comment by berkanteber** [comment]
All tagged from v2.0.0 onward.

**Comment by joelpurra** [comment]
@berkanteber: are you sure you pushes the tags? Seem to be missing at least two untagged v2+ releases.

- https://github.com/putdotio/putio-kodi/tags
- https://github.com/putdotio/putio-kodi/commits/7429c27e49e600036f2035b572651796dd8b8b46/addon.xml

**Comment by berkanteber** [comment]
> I see all these on this link: 2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 3.0.0, 3.0.1.

3.0.2 was missing, added. 3.1.0 has just been approved, added.

**Comment by joelpurra** [comment]
@berkanteber: v3.0.2 was the one I primarily had in mind. Also found v2.3.2.

- https://github.com/putdotio/putio-kodi/pull/13
- https://github.com/putdotio/putio-kodi/commit/d94b5c0abc243dba9e419f1e1b80729be0478854

Glad to see that v3.1.0 was approved, thanks!

**Comment by berkanteber** [comment]
I don't think 2.3.2 is ever released. I don't see see it [here](https://github.com/xbmc/repo-plugins/pulls?q=putio). Maybe it was planned as 2.3.2 but directly released as 3.0.0, @BatuAksoy do you remember?

**Comment by joelpurra** [comment]
@berkanteber: ah, yes, that might be. #13 was not merged until a few days later, seemingly coinciding with working on v3.0.0. (The second missing tag I had in mind was actually originally v3.1.0, but it also had not yet been approved.)

**Comment by BatuAksoy** [comment]
Yes exactly as you said.
I was working on v19 upgrade but then I noticed there are other bigger changes required, so I submit 3.0.0 for release instead
